# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5.QtGui import QIcon
import os

from tab1 import traning1
from tab2 import predict_text1, create_excel, save_file
from config import Config


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 500))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setStyleSheet("color: rgb(0, 2, 127);font: 15pt")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_train_path = QtWidgets.QPushButton(self.tab_1)
        self.btn_train_path.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_train_path.setObjectName("btn_train_path")
        self.gridLayout_2.addWidget(self.btn_train_path, 0, 2, 1, 1)
        self.ip_train_path = QtWidgets.QLineEdit(self.tab_1)
        self.ip_train_path.setObjectName("ip_train_path")
        self.gridLayout_2.addWidget(self.ip_train_path, 0, 1, 1, 1)
        self.btn_test_path = QtWidgets.QPushButton(self.tab_1)
        self.btn_test_path.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_test_path.setObjectName("btn_test_path")
        self.gridLayout_2.addWidget(self.btn_test_path, 1, 2, 1, 1)
        self.ip_test_path = QtWidgets.QLineEdit(self.tab_1)
        self.ip_test_path.setObjectName("ip_test_path")
        self.gridLayout_2.addWidget(self.ip_test_path, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 9)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cb_algorithm = QtWidgets.QComboBox(self.tab_1)
        self.cb_algorithm.setObjectName("cb_algorithm")
        self.cb_algorithm.addItem("")
        self.cb_algorithm.addItem("")
        self.gridLayout_4.addWidget(self.cb_algorithm, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gb_config_svm = QtWidgets.QGroupBox(self.tab_1)
        self.gb_config_svm.setMinimumSize(QtCore.QSize(305, 0))
        self.gb_config_svm.setObjectName("gb_config_svm")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gb_config_svm)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_12 = QtWidgets.QLabel(self.gb_config_svm)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cb_Kernel = QtWidgets.QComboBox(self.gb_config_svm)
        self.cb_Kernel.setObjectName("cb_Kernel")
        self.cb_Kernel.addItem("")
        self.cb_Kernel.addItem("")
        self.cb_Kernel.addItem("")
        self.cb_Kernel.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_Kernel)
        self.ip_svm_c = QtWidgets.QDoubleSpinBox(self.gb_config_svm)
        self.ip_svm_c.setMinimum(0.0)
        self.ip_svm_c.setObjectName("ip_svm_c")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ip_svm_c)
        self.label_9 = QtWidgets.QLabel(self.gb_config_svm)
        self.label_9.setObjectName("label_9")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.gridLayout_10.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.gb_config_svm)
        self.gb_config_nvb = QtWidgets.QGroupBox(self.tab_1)
        self.gb_config_nvb.setMinimumSize(QtCore.QSize(305, 0))
        self.gb_config_nvb.setObjectName("gb_config_nvb")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gb_config_nvb)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.gb_config_nvb)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.ip_nvb_alpha = QtWidgets.QDoubleSpinBox(self.gb_config_nvb)
        self.ip_nvb_alpha.setObjectName("ip_nvb_alpha")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ip_nvb_alpha)
        self.gridLayout_11.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.gb_config_nvb)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.btn_train = QtWidgets.QPushButton(self.tab_1)
        self.btn_train.setEnabled(True)
        self.btn_train.setObjectName("btn_train")
        self.gridLayout_4.addWidget(self.btn_train, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.lb_percent = QtWidgets.QLabel(self.tab_1)
        self.lb_percent.setMinimumSize(QtCore.QSize(305, 0))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lb_percent.setFont(font)
        self.lb_percent.setStyleSheet("color: rgb(0, 139, 0); font: 19pt")
        self.lb_percent.setText("")
        self.lb_percent.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_percent.setObjectName("lb_percent")
        self.horizontalLayout_2.addWidget(self.lb_percent)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ip_predict_path = QtWidgets.QLineEdit(self.tab_2)
        self.ip_predict_path.setObjectName("ip_predict_path")
        self.gridLayout_6.addWidget(self.ip_predict_path, 0, 1, 1, 1)
        self.btn_file_predict_path = QtWidgets.QPushButton(self.tab_2)
        self.btn_file_predict_path.setObjectName("btn_file_predict_path")
        self.gridLayout_6.addWidget(self.btn_file_predict_path, 0, 2, 1, 1)
        self.btn_predict_file = QtWidgets.QPushButton(self.tab_2)
        self.btn_predict_file.setObjectName("btn_predict_file")
        self.gridLayout_6.addWidget(self.btn_predict_file, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.cb_models = QtWidgets.QComboBox(self.tab_2)
        self.cb_models.setObjectName("cb_models")
        self.cb_models.addItem("")
        self.cb_models.addItem("")
        self.gridLayout_6.addWidget(self.cb_models, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 2)
        self.gridLayout_6.setColumnStretch(1, 10)
        self.gridLayout_6.setColumnStretch(2, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 2, 0, 1, 1)
        self.lb_predict1 = QtWidgets.QLabel(self.tab_2)
        self.lb_predict1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_predict1.setObjectName("lb_predict1")
        self.gridLayout_3.addWidget(self.lb_predict1, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_predict2 = QtWidgets.QLabel(self.tab_2)
        self.lb_predict2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_predict2.setObjectName("lb_predict2")
        self.horizontalLayout.addWidget(self.lb_predict2)
        self.lb_predict3 = QtWidgets.QLabel(self.tab_2)
        self.lb_predict3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_predict3.setObjectName("lb_predict3")
        self.horizontalLayout.addWidget(self.lb_predict3)
        self.lb_predict4 = QtWidgets.QLabel(self.tab_2)
        self.lb_predict4.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_predict4.setObjectName("lb_predict4")
        self.horizontalLayout.addWidget(self.lb_predict4)
        self.gridLayout_3.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.lb_predict = QtWidgets.QLabel(self.tab_2)
        self.lb_predict.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_predict.setObjectName("lb_predict")
        self.gridLayout_3.addWidget(self.lb_predict, 4, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.lb_predict.setStyleSheet("color: rgb(0, 139, 0); font: 18pt")
        self.lb_predict1.setStyleSheet("color: rgb(0, 2, 127); font: 22pt")
        self.lb_predict2.setStyleSheet("color: rgb(0, 139, 0); font: 16pt")
        self.lb_predict3.setStyleSheet("color: rgb(0, 139, 0); font: 16pt")
        self.lb_predict4.setStyleSheet("color: rgb(0, 139, 0); font: 16pt")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Tab 1
        self.btn_train_path.clicked.connect(self.import_file_train)
        self.btn_test_path.clicked.connect(self.import_file_test)
        self.btn_train.clicked.connect(self.train_model)

        self.cb_algorithm.currentIndexChanged.connect(self.change_config)
        self.change_config(0)

        # Tab2
        # predict file
        self.btn_file_predict_path.clicked.connect(self.import_file_predict)
        self.btn_predict_file.clicked.connect(self.predict_file)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Text classification"))
        self.btn_train_path.setText(_translate("MainWindow", "chọn tập tin"))
        self.btn_test_path.setText(_translate("MainWindow", "chọn tập tin"))
        self.label.setText(_translate("MainWindow", "tập tin huấn luyện"))
        self.label_3.setText(_translate("MainWindow", "tập tin kiểm tra"))
        self.cb_algorithm.setItemText(0, _translate("MainWindow", "Naive Bayes"))
        self.cb_algorithm.setItemText(1, _translate("MainWindow", "SVM"))
        self.gb_config_svm.setTitle(_translate("MainWindow", "tham số SVM"))
        self.label_12.setText(_translate("MainWindow", "Kernel"))
        self.cb_Kernel.setItemText(0, _translate("MainWindow", "Linear Kernel"))
        self.cb_Kernel.setItemText(1, _translate("MainWindow", "Gaussian RBF"))
        self.cb_Kernel.setItemText(2, _translate("MainWindow", "Polynomial Kernel"))
        self.cb_Kernel.setItemText(3, _translate("MainWindow", "Sigmoid Kernel"))
        self.label_9.setText(_translate("MainWindow", "C"))
        self.gb_config_nvb.setTitle(_translate("MainWindow", "tham số NBC"))
        self.label_11.setText(_translate("MainWindow", "Alpha"))
        self.btn_train.setText(_translate("MainWindow", "bắt đầu"))
        self.label_4.setText(_translate("MainWindow", "thuật toán"))
        self.label_6.setText(_translate("MainWindow", "cấu hình"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "huấn luyện"))
        self.btn_file_predict_path.setText(_translate("MainWindow", "chọn tập tin"))
        self.btn_predict_file.setText(_translate("MainWindow", "đánh giá"))
        self.label_5.setText(_translate("MainWindow", "tập tin cần đánh giá"))
        self.cb_models.setItemText(0, _translate("MainWindow", "NBC"))
        self.cb_models.setItemText(1, _translate("MainWindow", "SVM"))
        self.label_8.setText(_translate("MainWindow", "mô hình"))
        self.lb_predict1.setText(_translate("MainWindow", "đánh giá"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "đánh giá"))
    def change_config(self, value):
        if value == 0:
            self.gb_config_svm.hide()
            self.gb_config_nvb.show()
        elif value == 1:
            self.gb_config_svm.show()
            self.gb_config_nvb.hide()

    def import_file_train(self):
        self.open_dialog_box('train')

    def import_file_test(self):
        self.open_dialog_box('test')

    def import_file_predict(self):
        self.open_dialog_box('predict_file')

    def open_dialog_box(self, name):
        filename = QFileDialog.getOpenFileName(filter="Excel (*.xls *.xlsx)")
        path = filename[0]

        if name == 'train':
            self.ip_train_path.setText(path)
        elif name == 'test':
            self.ip_test_path.setText(path)
        elif name == 'predict_file':
            self.ip_predict_path.setText(path)

    def get_config(self, algorithm_index):
        if algorithm_index == 0:
            alpha = self.ip_nvb_alpha.value()
            model_name="NBC12"
            return Config(alpha=alpha), model_name

        elif algorithm_index == 1:
            model_name="SVM12"
            C = self.ip_svm_c.value()
            if(self.cb_Kernel.currentIndex()== 0):
                kernel = 'linear'
            if (self.cb_Kernel.currentIndex() == 1):
                kernel = 'rbf'
            if(self.cb_Kernel.currentIndex() == 2):
                kernel = 'poly'
            if (self.cb_Kernel.currentIndex() == 3):
                kernel = 'sigmoid'
            return Config(C=C, kernel=kernel), model_name

    def train_model(self):
        train_path = self.ip_train_path.text()
        test_path = self.ip_test_path.text()
        algorithm_index = self.cb_algorithm.currentIndex()
        algorithm_config, model_name = self.get_config(algorithm_index)

        result =  str(traning1(train_path, test_path,model_name, algorithm_index, algorithm_config))

        self.lb_percent.setText(result)

    # Tab 2

    def predict_file(self):
        file_path = self.ip_predict_path.text()
        if (self.cb_models.currentIndex() == 0):
            model_name = 'NBC12' + '.pkl'
        if (self.cb_models.currentIndex() == 1):
            model_name = 'SVM12'+ '.pkl'
        create_excel(file_path, model_name)

        labels,k,l,n = create_excel(file_path, model_name)
        sum = k+l+n

        name = QFileDialog.getSaveFileName(caption='Save file', filter="Excel (*.xlsx *.xls)")

        save_file(name, file_path, labels)
        #
        self.lb_predict.setText(("Tìm thấy " +str(sum)+ " phản hồi của người học "))
        self.lb_predict2.setText((str(k) + " Đánh giá tích cực "))
        self.lb_predict3.setText((str(l) + " Đánh giá tiêu cực "))
        self.lb_predict4.setText((str(n) + " Đánh giá trung tính "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
